base_url = "https://xd009642.github.io"
title = "xd009642"
description = "Software engineer doing stuff in Rust, recovering C++ programmer. Using this as a place to talk about my current projects including the Rust code coverage tool tarpaulin"
theme = "apollo"
compile_sass = true
generate_feeds = true
feed_filenames = ["atom.xml"]
build_search_index = true
taxonomies = [{ name = "tags" }]

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
smart_punctuation = true

[markdown.highlighting]
style = "class"
light_theme = "github-light"
dark_theme = "github-dark"
error_on_missing_language = false

[extra]
toc = true
use_cdn = false
theme = "toggle"
fancy_code = true
dynamic_note = true
mathjax = true
repo_url = "https://github.com/xd009642/xd009642.github.io/tree/main/content/"

menu = [
    { name = "/posts", url = "/", weight = 1 },
    { name = "/about", url = "/about", weight = 2 },
]

socials = [
    { name = "github", url = "https://github.com/xd009642", icon = "github" },
]

stylesheets = []

[extra.taxonomies]
sort_by = "page_count"
reverse = true

[extra.analytics]
enabled = false

[extra.analytics.goatcounter]
user = ""
host = "goatcounter.com"

[extra.analytics.umami]
website_id = ""
host_url = "https://api-gateway.umami.dev/"

[extra.analytics.google]
tracking_id = ""
